### ISSUE TITLE
Error in UEFI install

### ISSUE THREAD

**Issue by ikidd** [danboid/ALEZ#26]
Trying to install on a UEFI only system (2011 Macbook Pro).  I get the zpool created fine, but when it goes into the section to create the ESP, it fails immediately after "View partition layout before creating esp?" whether you say yes or no.  It throws:

ls: cannot access '': no such file or directory

Error: Expected 2 arguments, found only 1.
Use --help to list options

Then goes on to unmount datasets, etc.

Following through the script, it looks like it's failing on get_parts or update_parts, around about line 552.

**Comment by danboid** [comment]
That should be fixed now. Try again please.

**Comment by sdirkwinkel** [comment]
I've just tried this too and I'm getting the same error.
I can't see the "ls: ..." line because of the blue background.
If you've got another update or something I can try it again

**Comment by danboid** [comment]
Hi @0xQSL 

You're trying to do a UEFI install too? Have you tried in the last 5 hours since my latest commit?

**Comment by sdirkwinkel** [comment]
yes, I've tried at the time i commented so about an hour ago

**Comment by ikidd** [comment]
Still fails at same place for me.  If you'd like to add debugs for line #s or such I can report them back or post a logfile.

Edit:  So I put in some echos and found it's failing on the  line

    esp=$(dialog --stdout --clear --title "Install type" \
                 --menu "$msg" \
                 $HEIGHT $WIDTH "$(( 2 + plength))" "${partinfo}")

**Comment by danboid** [comment]
Seems to be fixed now. UEFI/systemd install is working again at least.

**Comment by danboid** [comment]
I've done a UEFI/GRUB install now too. All looks good again here.

**Comment by danboid** [comment]
"Works for me" but let me know if you still have probs.
